### ISSUE TITLE
`overwrite` option in `.dest()`

### ISSUE THREAD

**Issue by sindresorhus** [wearefractal/vinyl-fs#30]
It would be useful if `.dest()` had an option to not overwrite existing files.

Use-case: You build a lot of stuff into a `dist` folder and you want a task to copy all the files that weren't already processed by the pipeline. Yes you could do some trickery with streams, but this would be much easier.

**Comment by JaKXz** [comment]
It'd be awesome to see this.

**Comment by domoritz** [comment]
:+1:

**Comment by gad2103** [comment]
+1

**Comment by gittycat** [comment]
+1

**Comment by contra** [comment]
Instead of +1 maybe you should think about sending a pull request...

**Comment by zxqfox** [comment]
@contra :+1:

**Comment by contra** [comment]
closed by #59

**Comment by phillip-haydon** [comment]
Was this removed? It doesn't work...

**Comment by nillis** [comment]
@phillip-haydon +1

**Comment by zxqfox** [comment]
> Was this removed? It doesn't work...

This is implemented to master. Guess it won't be backported to 3.x.
https://github.com/gulpjs/vinyl-fs/pull/59

**Comment by phated** [comment]
All vinyl code is essentially "backported" to 3.x - There are breaking changes so we can't include it as a dependency to gulp but you can change your `gulp.src` and `gulp.dest` calls to `vinylfs.src` and `vinylfs.dest` calls and stuff will continue to work, but take a look at the breaking changes before you swap everything out.
