### ISSUE TITLE
Symlinked directories cause EISDIR error from `vinyl-fs.src()`

### ISSUE THREAD

**Issue by pghalliday** [wearefractal/vinyl-fs#39]
The fix for #38 is causing me issues when I have symlinked directories. In my use case I want to follow symlinks and copy their contents, etc. However the use of `lstat` causes `vinyl-fs` to think symlinked directories are files and I think it tries to load their content resulting in EISDIR errors.

I have created the following project to demonstrate the problem

https://github.com/pghalliday/test-vinyl-fs

**Comment by nahidakbar** [comment]
bump?

**Comment by tkalfigo** [comment]
I'm also running into this. Anyone figured out a workaround?

**Comment by valeriangalliat** [comment]
We also reproduce this error in @SassDoc. There's no stack trace on this `EISDIR` error, but I could manually trace it [here](https://github.com/wearefractal/vinyl-fs/blob/141ff43302dec6535d086cf27d538530161952c5/lib/src/getContents/bufferFile.js#L9).

So it appears not to be a problem with node-glob; maybe [this function](https://github.com/wearefractal/vinyl/blob/ec094b43e36512894142baacef26dfffc5827114/index.js#L44) should be returning true when the file is a symlink to a directory?

**Comment by contra** [comment]
@valeriangalliat That runs a stat on each file twice (once in getStats, once in resolveSymlinks)

**Comment by valeriangalliat** [comment]
Totally, hence me qualifying it as "rather dirty". :/

But maybe propagating the stats object in `resolveSymlinks` and getting rid of the `getStats` pipe is an acceptable solution? If so I can provide a PR for this.

**Comment by contra** [comment]
@valeriangalliat Yep, or make getStats resolve symlinks
