### ISSUE TITLE
Write relative symbolic links in `dest`

### ISSUE THREAD

**Issue by lexi-lambda** [wearefractal/vinyl-fs#50]
Currently, symlinks are simply ignored by `dest`—nothing at all is written. This is problematic when trying to write Mac OS X `.framework` bundles, since they heavily depend on proper symlink structure for to manage their resources.

A real example in which this is an issue is in the [`gulp-atom-shell`](https://github.com/joaomoreno/gulp-atom-shell) package. Currently it handles this by writing ZIP files using [`gulp-vinyl-zip`](https://github.com/joaomoreno/gulp-vinyl-zip), which writes the symlinks properly, but this layer of indirection is inconvenient.

It would be nice if relative symlinks could be preserved in the output of `dest`.

**Comment by contra** [comment]
We already added .symlink to vinyl-fs which will be updated in for gulp 4

For a temporary fix you can `npm install vinyl-fs` and use the .symlink function until it is built into the gulp module

**Comment by lexi-lambda** [comment]
@contra Perhaps I'm simply incorrect, but I was under the impression that `symlink` was only for explicitly creating symlinks from any stream. I'm asking for files which are already symlinks in the input to be preserved in the output of the ordinary `dest` function.

**Comment by limulus** [comment]
I’ve run into this issue as well, in my case with trying to add symbolic link support to the [`gulp-untar`](https://www.npmjs.com/package/gulp-untar) package. I’m a bit too new to Gulp to know what the right solution is, but it strikes me that `.dest()` should probably write a symlink if `(file.stat.mode & 0170000) === 0120000)` — the mode for symbolic links [per `stat-mode`](https://github.com/TooTallNate/stat-mode/blob/master/index.js#L18). The destination of the symlink could simply be provided by `file.contents`.

**Comment by phated** [comment]
@contra was this resolved by #85?

**Comment by contra** [comment]
Yep!
