### ISSUE TITLE
Question- Streaming - Batch Style For Files Better Performance? 

### ISSUE THREAD

**Issue by dman777** [wearefractal/vinyl-fs#58]
Hello, I am under the impression that gulp.src('*.css') grabs all the files and pipes them out one at a time...because when I do 

```javascript
gulp.src('./css/*.cssl')
    .pipe(through2.obj(function(obj, enc, next) {
    console.log(object.history[0]);
    next();
  })) 
```

`object.history[0]` shows one file at a time. 

My question is, please:
Is there a performance benefit with a batch style in the code on the bottom? Or  is it better(performance and efficiency) to do the stream default one at time file pipe out? Let's say...for like 2000 files.

```javascript

var files = [];
gulp.src('./css/*.css')
    .pipe(through2.obj(function(obj, enc, next) {
        file = obj.history[0].split("/").pop();
        files.push(file);
        next();
     }, function(flushcb) {
            flushcb();
            files = doSomethingWithFileBatch(files)
            //pipe out files
       }
   }));

````

**Comment by contra** [comment]
One at a time. If you do 2000 at once you are going to block the main thread for longer and prevent other work from being done.

**Comment by dman777** [comment]
But with I/O operations, it is none blocking...correct?

**Comment by contra** [comment]
@dman777 http://blog.mixu.net/2011/02/01/understanding-the-node-js-event-loop/
