### ISSUE TITLE
dest to support array of paths

### ISSUE THREAD

**Issue by ericnewton76** [wearefractal/vinyl-fs#67]
dest outFolder seems to support 'string' and 'function' but not an array of strings

would be nice to specify a dest as an array of strings, which would then write files in a loop.  will probably send a pull request

**Comment by ericnewton76** [comment]
So i'm using gulp which is using v0.3 of vinyl fs and I had a version that would take an array of strings for outFolder and iterate them individually 

```javascript
  //note this is psuedo code, i accidentally lost real version
  var folderEntries;
  if(outFolder !== '[object Array]') 
     folderEntries = []; folderEntries.push(outFolder);
  else
     folderEntries = outFolder;

  folderEntries.forEach(function(outFolder) {

(wraps original index.js code in v0.3)

   })
```

**Comment by kevva** [comment]
You could probably use this (assuming you're using gulp):

```js
.pipe(gulp.dest('dest'))
.pipe(gulp.dest('build'));
```

**Comment by ericnewton76** [comment]
It's kinda dynamic though, we're trying to make our gulpfile somewhat project agnostic except for certain configuration

```javascript
Project 1:   var CSS_DEST = "/assets/css";
Project 2:   var CSS_DEST = ["/assets/css","../site_aspx/assets/css","../site_prod/assets/css"];
```
```javascript
gulp.src(SASS_FILES)
  .pipe(sass( { ... } ))
  .pipe(gulp.dest(CSS_DEST))
```

**Comment by phated** [comment]
You can just iterate over the array and generate your streams and pipe to each one.  I don't suggest your strategy of making everything generic, especially when your paths aren't.

**Comment by kevva** [comment]
As @phated says. You could just do this:

```js
function dest(paths) {
	paths.forEach(function (path) {
		gulp.dest(path);
	});
}

gulp.task('default', function () {
	gulp.src('src/**/*')
		.pipe(dest(['dest', 'build']));
});
```

**Comment by kevva** [comment]
Yup, as @phated says, something like this would work:

```js
var gulp = require('gulp');
var streamCombiner = require('stream-combiner');

function dest(paths) {
    var arr = [];

    arr = paths.map(function (path) {
        return gulp.dest(path);
    });

    return streamCombiner(arr);
}

gulp.task('default', function () {
    gulp.src('src/**/*')
        .pipe(dest(['dest', 'build']));
});
```

**Comment by stevemao** [comment]
Is the problem solved? This could be added to the docs IMO.

**Comment by phated** [comment]
@contra do you agree with the solution provided in https://github.com/wearefractal/vinyl-fs/issues/67#issuecomment-97137540 ? I can submit a PR adding it to the docs.

**Comment by contra** [comment]
Yeah, this is resolved

**Comment by tkrotoff** [comment]
Would look legit to me for src() and dest() to provide symmetric/same APIs:
`src(globs[, opt])` and `dest(globs[, opt])` instead of `dest(folder[, opt])`
=> easier for users, less thinking.
The [`streamCombiner` thing](https://github.com/gulpjs/vinyl-fs/issues/67#issuecomment-97137540) could be done by vinyl-fs itself.

**Comment by stevemao** [comment]
`dest(globs[, opt])` globs is a file matching pattern. how do you match a file that may not exist?

**Comment by tkrotoff** [comment]
@stevemao you are right, I've edited my comment and replace `dest(globs[, opt])` by `dest(folders[, opt])`

**Comment by stevemao** [comment]
How would that work? is `folers` an `array`?

**Comment by tkrotoff** [comment]
@stevemao yes
Rewording: having src(glob**s**[, opt]) and dest(folder**s**[, opt]) make the APIs symmetric which I believe is good.
src => **array** of globs
dest => **array** of folders (instead of 1 folder)

I was surprised when writing a gulpfile.js to discover that dest() did not take an array.

**Comment by stevemao** [comment]
I would prefer to do it with streamCombiner and keep this one as simple as possible.

**Comment by ericnewton76** [comment]
So where does this issue stand?  

Of course being the OP, I'm biased towards the dest => array of folders option encouraged by @tkrotoff
