### ISSUE TITLE
No way to override UTF-8 BOM stripping

### ISSUE THREAD

**Issue by IsaacSanch** [wearefractal/vinyl-fs#72]
Having been working with gulp (and vinyl-fs by proxy) for a while now, I have become aware that vinyl-fs strips the BOM from UTF-8 files. This is currently completely undocumented (except a footnote in the changelog) and yet potentially effects any system that needs to have BOM present in output files. (IIS / ASP.NET is an example that can occasionally be picky with the output of UTF8 files that lack BOM.) Providing users with a flag to override this behavior would be helpful for these edge cases.

**Comment by contra** [comment]
@sindresorhus any comment?

**Comment by contra** [comment]
@IsaacSanch Will get this resolved :+1:

**Comment by contra** [comment]
Oops meant to ping @mathiasbynens

**Comment by sindresorhus** [comment]
The BOM in UTF-8 has no meaning.

> This is currently completely undocumented

It's normal to remove the BOM as it conflicts with many things, like JSON.parse, etc. You should just get in the habit of assuming it's getting stripped. Even Node does this when you `require` files.

> Providing users with a flag to override this behavior would be helpful for these edge cases.

:-1: Just add it back if you need it. There really shouldn't be a flag for something like this.

**Comment by contra** [comment]
Adding my comment from the commit here for visibility -

@sindresorhus Not adding it just because it was asked for, adding it because it makes sense. We shouldn't be fucking with contents without a way to disable it or we are a really shitty general purpose fs access tool (vinyl-fs)

**Comment by sindresorhus** [comment]
@contra The strip BOM functionality is *fixing* a bug for users. UTF-8 shouldn't have a BOM. Now *every* gulp plugin will have to handle BOM stripping in case `stripBOM: false`...

**Comment by phated** [comment]
:+1: with @sindresorhus here - we should always remove when encoding is `utf8`

**Comment by contra** [comment]
If this is an opinionated view we want to take on reading files then it needs to be documented

**Comment by contra** [comment]
Resolution: Use something prior to .dest to add the BOM back to your files if you encounter this edge-case. https://www.npmjs.com/package/vinyl-map is a good place to start :+1: 

When you come up with working code please post it here so others can see it.

**Comment by phated** [comment]
Probably just create the inverse of https://www.npmjs.com/package/gulp-stripbom

**Comment by sindresorhus** [comment]
@phated Yup, was going to suggest that.

Done: https://github.com/sindresorhus/gulp-bom

**Comment by contra** [comment]
Locking since this is resolved :+1:
