### ISSUE TITLE
Windows: symlink links made for directories instead of symlinkd

### ISSUE THREAD

**Issue by macromaniac** [wearefractal/vinyl-fs#74]
Howdy,

Currently when I use your symlink function i'm only getting SYMLINK files, even if the items in the stream are directories.
```javascript
   fs.src("extension/*", { read: false })
      .pipe(fs.symlink("../bin/firefox/"));
```
creates the following:

![filelinkfordirectories](https://cloud.githubusercontent.com/assets/828529/8480011/d2c589ea-20a0-11e5-90ae-e0194b476306.PNG)

This is because fs requires you to specifiy if the type of the object is a file or directory for windows to create the proper link.  Once specified in [your symlink wrapper](https://github.com/wearefractal/vinyl-fs/blob/master/lib/symlink/index.js), the links to folders become SYMLINKD instead of SYMLINK and become accessible as directories:

![dirlinkfordirectories](https://cloud.githubusercontent.com/assets/828529/8480352/bf076372-20a2-11e5-9141-ad8538dd71e6.PNG)

This detail might be better handled by graceful-fs (if the functionality was added via a flag or something). Regardless, I'm willing to do a pr this sunday,

**Comment by macromaniac** [comment]
Capslock was a bit annoying and I accidently said system link instead of symlink (sym = symbolic not system).

**Comment by contra** [comment]
Yep we can do this, didn't notice this argument https://nodejs.org/api/fs.html#fs_fs_symlink_srcpath_dstpath_type_callback

**Comment by contra** [comment]
Can you try the master branch and see if that fixes it?

**Comment by macromaniac** [comment]
Nice. Master is looking A+ :ok_hand:
