### ISSUE TITLE
iojs: "Not compatible with your version of node/npm"?

### ISSUE THREAD

**Issue by rreusser** [wearefractal/vinyl-fs#80]
Preface: probably my error. Sorry to bother you.

I installed iojs (and immediately regretted it because it seemed to clobber my node installation—this is why I think it's my screwy issue.)

I run:

```
npm install vinyl-fs@0.3.9
```

I get:

```
npm install vinyl-fs@0.3.9
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "--save-dev" "vinyl-fs@0.3.9"
npm ERR! node v2.3.5-pre
npm ERR! npm  v2.13.0
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: vinyl-fs@0.3.9
npm ERR! notsup Required: {"node":">= 0.10"}
npm ERR! notsup Actual:   {"npm":"2.13.0","node":"2.3.5-pre"}

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rreusser/projects/node/gulp-latex/npm-debug.log
```

I can send over the npm-debug.log, but there's not much new info there. I can clone the repo, npm install, and the tests run just fine. This prevents gulp from installing, but it's not clear there's actually a problem beyond the version check itself.

**Comment by phated** [comment]
You are using a pre-release version of "node" (iojs) - notice the node version saying "2.3.5-pre" - prerelease versions don't match semver.

**Comment by rreusser** [comment]
Worked fine. I was aware of that in the abstract sense but hadn't had to confront what that really means yet. Thanks! Sorry for the noise!
