### ISSUE TITLE
Vinylfs fails to file larger than 1GB

### ISSUE THREAD

**Issue by zepedrorocha** [wearefractal/vinyl-fs#84]
I am trying something very simple: copy a file with more than 1GB:
     
    RangeError: File size is greater than possible Buffer: 0x3FFFFFFF bytes
    at evalmachine.<anonymous>:282:19
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)

the code in question is very simple:

      return fsv.src('C:\\my-src-dir\\huge-file.bin').pipe(fsv.dest('./output'))

(this happens also when using gulp.src and gulp.dest)

Any ideas?
Thx

**Comment by phated** [comment]
You can copy large files with vinyl-fs by turning streaming mode on.

```js
vfs.src(glob, { stream: true })
```

**Comment by contra** [comment]
Yep ^
