### ISSUE TITLE
Revisit watch in vinyl adapters

### ISSUE THREAD

**Issue by phated** [wearefractal/vinyl-fs#86]
Currently, watch is the redheaded step-child of gulp.  It doesn't work as part of the stream and it is weird to use with tasks.  Most people defer to the `gulp-watch` plugin for watching because they can put it in the stream and keep things DRY.

I see a few ways to "clean this up" for gulp 4:
1. Remove watch from the vinyl adapter spec and just have `gulp.watch` an alias of `chokidar.watch`
2. Keep the watch in the vinyl adapters but switch it to a stream (like `gulp-watch`)
3. At worst, just alias `vfs.watch` to `chokidar.watch`.  I really don't like this because we still have the problem of it being different than `src`, `dest` and `symlink` and it doesn't accept async-only gulp tasks.
4. Something totally different than I have thought up.

**Comment by es128** [comment]
Another angle to look at this from - what are the problems with the `gulp-watch` approach? What prevents that from being codified as the "standard" way to do fs watching for future gulp?

**Comment by phated** [comment]
I think the biggest "problem" is that it is a never-ending stream (at least that's what it looks like at my cursory glance) so you can't return it from your task, whereas I think it would be better to monkey patch `.pipe`, return a `lazypipe`, or something to start a new stream after the initial one completes.  cc'ing @floatdrop

**Comment by floatdrop** [comment]
@es128 @phated yep.

From usage experience - most simple and used way is implement `gulp.watch([globs...], [tasks...])` watcher. No endless streams, no globs rematching.

**Comment by es128** [comment]
So, @phated, a few times you referred to aliasing `chokidar.watch`. I suppose you didn't mean that literally - seems like it would be worth continuing to do a bit of simple wrapping to preserve the [existing API signatures](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb).

Or do you want to get rid of that too and let people just bind their own event listeners?

**Comment by contra** [comment]
Alright:

- Let's remove watch from vinyl-fs (and the vinyl adapter spec)
- Let's add a wrapper around chokidar to gulp, exposed as gulp.watch

I think streaming watch is overkill, and IMO that problem is solved with the new src `since` option + the new task system

**Comment by phated** [comment]
Sounds good.  To answer @es128's last question: we are just going to normalize the behavior with that of chokidar because the abstraction layers aren't worth the complexity and we are already making breaking changes.

**Comment by es128** [comment]
:+1: 

Let me know if you'd like me to pitch in to this effort. A simple wrapper to match the original API wouldn't be complex at all. 

If you're talking about stripping it down all the way to aliasing `chokidar.watch` as `gulp.watch`, then tbh if I were you I'd consider just recommending to users that they just directly use whatever watch lib/method they prefer (you could express a positive opinion for chokidar if you like :wink:) and drop the `gulp.watch` method entirely.

**Comment by phated** [comment]
@es128 In most cases, I would agree with your suggestion; However, we still need convenience over the watching globs and executing a task by task name API, so we will be keeping the watch API in gulp.

**Comment by contra** [comment]
@es128 We need a wrapper to minimize the # of breaking changes

**Comment by es128** [comment]
Yep sounds good, I agree that's the best way to go. 

If you'd like me to take a crack at a PR for gulp to do this just say the word.

**Comment by phated** [comment]
@es128 a PR to gulp would be much appreciated!
