### ISSUE TITLE
merge-stream version?

### ISSUE THREAD

**Issue by davidbarrows** [wearefractal/vinyl-fs#87]
Hi, sorry if this is a bit OCD but... I'm trying to tidy up some npm dependencies in a project by running "npm outdated" and getting the below message when trying to update merge-stream; is it possible you might consider updating your merge-stream dependency version?  Just thought I'd ask.  Thanks and regards -dB  (Ps, I may be reading that wrong; is it gulp-image-minify that has an outdated version of vinyl-fs?  But it seems vinyl-fs requires an older version of merge-stream.  Anyway)... 

davids-mbp:dBWeb davidwbarrows$ npm outdated
Package       Current  Wanted  Latest  Location
cli-color       0.3.3   0.3.3   1.0.0  cli-color
lodash          2.4.2   2.4.2  3.10.1  lodash
merge-stream    0.1.8   0.1.8   1.0.0  merge-stream
davids-mbp:dBWeb davidwbarrows$ npm update
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs requires merge-stream@'^0.1.7' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb/node_modules/merge-stream,
npm WARN unmet dependency which is version 1.0.0
merge-stream@1.0.0 node_modules/merge-stream
└── readable-stream@2.0.2 (process-nextick-args@1.0.2, inherits@2.0.1, isarray@0.0.1, util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

**Comment by contra** [comment]
Yep, we update our dependencies regularly. If you've found something out of date and want to fix it feel free to send a PR

**Comment by davidbarrows** [comment]
thank you

**Comment by davidbarrows** [comment]
created pull request 90.  This was my first ever PR.  Please be gentle :-D
